package syncer

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/myhro/ssh-keys/config"
	"github.com/myhro/ssh-keys/fetch"
	"github.com/myhro/ssh-keys/keys"
	"github.com/myhro/ssh-keys/state"
	"github.com/myhro/ssh-keys/store"
)

const header = "# Auto-generated by ssh-keys from %s\n# Local changes will be overwritten.\n"

type Syncer struct {
	Client *fetch.Client
	Config *config.Config
}

func New(cfg *config.Config) *Syncer {
	return &Syncer{
		Client: fetch.New(),
		Config: cfg,
	}
}

func (s *Syncer) Run(ctx context.Context) error {
	if !strings.HasPrefix(s.Config.URL, "https://") {
		slog.Warn("keys will be fetched over an insecure connection", "url", s.Config.URL)
	}

	target := store.New(s.Config.File)
	stateFile := state.New(s.Config.StateFile)

	cached, err := stateFile.Read()
	if err != nil {
		return err
	}

	etag, err := s.validator(target, cached)
	if err != nil {
		return err
	}

	res, err := s.Client.Get(ctx, s.Config.URL, etag)
	if err != nil {
		return err
	}
	if res.NotModified {
		slog.Info("keys are up to date", "file", target.Path)
		return nil
	}

	list := keys.New(res.Body)
	err = list.Validate()
	if err != nil {
		return err
	}

	content := s.content(list)
	err = target.Write(content)
	if err != nil {
		return err
	}
	slog.Info("keys updated", "file", target.Path, "keys", list.Count)

	return stateFile.Write(&state.Data{
		ETag:   res.ETag,
		SHA256: state.Digest(content),
	})
}

func (s *Syncer) validator(target *store.File, cached *state.Data) (string, error) {
	if cached.ETag == "" || cached.SHA256 == "" {
		return "", nil
	}

	content, err := target.Read()
	if err != nil {
		return "", err
	}
	if len(content) == 0 {
		return "", nil
	}
	if state.Digest(content) != cached.SHA256 {
		slog.Warn("keys file was modified outside ssh-keys, restoring", "file", target.Path)
		return "", nil
	}

	return cached.ETag, nil
}

func (s *Syncer) content(list *keys.List) []byte {
	return append([]byte(fmt.Sprintf(header, s.Config.URL)), list.Bytes()...)
}
