package syncer

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/crypto/ssh"

	"github.com/myhro/ssh-keys/internal/config"
	"github.com/myhro/ssh-keys/internal/fetch"
	"github.com/myhro/ssh-keys/internal/state"
)

type setup struct {
	File      string
	StateFile string
	Syncer    *Syncer
}

func publicKey(t *testing.T) string {
	t.Helper()

	pub, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generating key: %v", err)
	}
	key, err := ssh.NewPublicKey(pub)
	if err != nil {
		t.Fatalf("converting key: %v", err)
	}

	return strings.TrimSpace(string(ssh.MarshalAuthorizedKey(key)))
}

func newSetup(t *testing.T, handler http.HandlerFunc) *setup {
	t.Helper()

	server := httptest.NewServer(handler)
	t.Cleanup(server.Close)

	dir := t.TempDir()
	cfg := &config.Config{
		File:      filepath.Join(dir, "authorized_keys"),
		StateFile: filepath.Join(dir, "authorized_keys.ssh-keys"),
		URL:       server.URL,
	}

	return &setup{
		File:      cfg.File,
		StateFile: cfg.StateFile,
		Syncer: &Syncer{
			Client: fetch.New(),
			Config: cfg,
		},
	}
}

func read(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}

	return string(data)
}

func write(t *testing.T, path string, data string) {
	t.Helper()

	err := os.WriteFile(path, []byte(data), 0o600)
	if err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}

func readState(t *testing.T, path string) *state.Data {
	t.Helper()

	data := &state.Data{}
	err := json.Unmarshal([]byte(read(t, path)), data)
	if err != nil {
		t.Fatalf("decoding %s: %v", path, err)
	}

	return data
}

func writeSynced(t *testing.T, s *setup, content string, etag string) {
	t.Helper()

	write(t, s.File, content)
	err := state.New(s.StateFile).Write(&state.Data{
		ETag:   etag,
		SHA256: state.Digest([]byte(content)),
	})
	if err != nil {
		t.Fatalf("writing %s: %v", s.StateFile, err)
	}
}

func TestRun(t *testing.T) {
	key := publicKey(t)
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("ETag", `"abc123"`)
		w.Write([]byte(key))
	})

	err := s.Syncer.Run(context.Background())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := read(t, s.File)
	if !strings.HasPrefix(content, "# Auto-generated by ssh-keys from ") {
		t.Fatalf("expected a generated header, got %q", content)
	}
	if !strings.HasSuffix(content, key+"\n") {
		t.Fatalf("expected the file to end with the key, got %q", content)
	}

	cached := readState(t, s.StateFile)
	if cached.ETag != `"abc123"` {
		t.Fatalf(`expected "abc123", got %q`, cached.ETag)
	}
	if cached.SHA256 != state.Digest([]byte(content)) {
		t.Fatalf("expected the digest of the written file, got %q", cached.SHA256)
	}
}

func TestRunNotModified(t *testing.T) {
	sent := ""
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		sent = r.Header.Get("If-None-Match")
		w.WriteHeader(http.StatusNotModified)
	})
	writeSynced(t, s, "current keys\n", `"abc123"`)

	err := s.Syncer.Run(context.Background())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if sent != `"abc123"` {
		t.Fatalf("expected the cached etag to be sent, got %q", sent)
	}
	content := read(t, s.File)
	if content != "current keys\n" {
		t.Fatalf("expected the file to be untouched, got %q", content)
	}
}

func TestRunIgnoresETagWithoutIntactKeysFile(t *testing.T) {
	tests := []struct {
		name    string
		content string
		missing bool
		cached  *state.Data
	}{
		{
			name:    "missing keys file",
			missing: true,
			cached:  &state.Data{ETag: `"abc123"`, SHA256: state.Digest([]byte("current keys\n"))},
		},
		{
			name:    "empty keys file",
			content: "",
			cached:  &state.Data{ETag: `"abc123"`, SHA256: state.Digest([]byte("current keys\n"))},
		},
		{
			name:    "locally modified keys file",
			content: "current keys\nssh-ed25519 injected\n",
			cached:  &state.Data{ETag: `"abc123"`, SHA256: state.Digest([]byte("current keys\n"))},
		},
		{
			name:    "missing state",
			content: "current keys\n",
		},
		{
			name:    "digest recorded without an etag",
			content: "current keys\n",
			cached:  &state.Data{SHA256: state.Digest([]byte("current keys\n"))},
		},
		{
			name:    "etag recorded without a digest",
			content: "current keys\n",
			cached:  &state.Data{ETag: `"abc123"`},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			key := publicKey(t)
			sent := "unset"
			s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
				sent = r.Header.Get("If-None-Match")
				w.Write([]byte(key + "\n"))
			})
			if !tc.missing {
				write(t, s.File, tc.content)
			}
			if tc.cached != nil {
				err := state.New(s.StateFile).Write(tc.cached)
				if err != nil {
					t.Fatalf("writing %s: %v", s.StateFile, err)
				}
			}

			err := s.Syncer.Run(context.Background())
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if sent != "" {
				t.Fatalf("expected no etag to be sent, got %q", sent)
			}

			content := read(t, s.File)
			if !strings.HasSuffix(content, key+"\n") {
				t.Fatalf("expected the remote keys to be restored, got %q", content)
			}
			if strings.Contains(content, "injected") {
				t.Fatalf("expected the local modification to be gone, got %q", content)
			}
			if digest := readState(t, s.StateFile).SHA256; digest != state.Digest([]byte(content)) {
				t.Fatalf("expected the digest of the written file, got %q", digest)
			}
		})
	}
}

func TestRunUnreadableState(t *testing.T) {
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		t.Error("expected no request to be made")
	})
	s.Syncer.Config.StateFile = t.TempDir()

	err := s.Syncer.Run(context.Background())
	if err == nil {
		t.Fatal("expected an error, got nil")
	}
}

func TestRunKeepsCurrentKeysOnFailure(t *testing.T) {
	tests := []struct {
		name   string
		status int
		body   string
	}{
		{
			name:   "invalid key",
			status: http.StatusOK,
			body:   "ssh-ed25519 not-a-real-key\n",
		},
		{
			name:   "empty body",
			status: http.StatusOK,
		},
		{
			name:   "not found",
			status: http.StatusNotFound,
			body:   "404 page not found\n",
		},
		{
			name:   "server error",
			status: http.StatusInternalServerError,
			body:   "boom\n",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("ETag", `"new"`)
				w.WriteHeader(tc.status)
				w.Write([]byte(tc.body))
			})
			writeSynced(t, s, "current keys\n", `"abc123"`)

			err := s.Syncer.Run(context.Background())
			if err == nil {
				t.Fatal("expected an error, got nil")
			}

			content := read(t, s.File)
			if content != "current keys\n" {
				t.Fatalf("expected the file to be untouched, got %q", content)
			}

			cached := readState(t, s.StateFile)
			if cached.ETag != `"abc123"` {
				t.Fatalf("expected the state to be untouched, got %q", cached.ETag)
			}
			if cached.SHA256 != state.Digest([]byte(content)) {
				t.Fatalf("expected the state to be untouched, got %q", cached.SHA256)
			}
		})
	}
}

func TestRunWithoutETagHeader(t *testing.T) {
	key := publicKey(t)
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(key + "\n"))
	})

	err := s.Syncer.Run(context.Background())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	cached := readState(t, s.StateFile)
	if cached.ETag != "" {
		t.Fatalf("expected no etag to be recorded, got %q", cached.ETag)
	}
	if cached.SHA256 != state.Digest([]byte(read(t, s.File))) {
		t.Fatalf("expected the digest of the written file, got %q", cached.SHA256)
	}
}

func TestRunWriteFailure(t *testing.T) {
	key := publicKey(t)
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(key + "\n"))
	})
	s.Syncer.Config.File = filepath.Join(filepath.Dir(s.File), "missing", "authorized_keys")

	err := s.Syncer.Run(context.Background())
	if err == nil {
		t.Fatal("expected an error, got nil")
	}
	if _, err := os.Stat(s.StateFile); !os.IsNotExist(err) {
		t.Fatal("expected no state to be recorded")
	}
}
