package syncer

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/myhro/ssh-keys/internal/config"
	"github.com/myhro/ssh-keys/internal/fetch"
	"github.com/myhro/ssh-keys/internal/keys"
	"github.com/myhro/ssh-keys/internal/store"
)

const header = "# Auto-generated by ssh-keys from %s\n# Local changes will be overwritten.\n"

type Syncer struct {
	Client *fetch.Client
	Config *config.Config
}

func New(cfg *config.Config) *Syncer {
	return &Syncer{
		Client: fetch.New(),
		Config: cfg,
	}
}

func (s *Syncer) Run(ctx context.Context) error {
	if !strings.HasPrefix(s.Config.URL, "https://") {
		slog.Warn("keys will be fetched over an insecure connection", "url", s.Config.URL)
	}

	target := store.New(s.Config.File)
	etagFile := store.New(s.Config.ETagFile)

	etag := ""
	if target.Exists() {
		cached, err := etagFile.Read()
		if err != nil {
			return err
		}
		etag = cached
	}

	res, err := s.Client.Get(ctx, s.Config.URL, etag)
	if err != nil {
		return err
	}
	if res.NotModified {
		slog.Info("keys are up to date", "file", target.Path)
		return nil
	}

	list := keys.New(res.Body)
	err = list.Validate()
	if err != nil {
		return err
	}

	err = target.Write(s.content(list))
	if err != nil {
		return err
	}
	slog.Info("keys updated", "file", target.Path, "keys", list.Count)

	if res.ETag == "" {
		return nil
	}
	return etagFile.Write([]byte(res.ETag + "\n"))
}

func (s *Syncer) content(list *keys.List) []byte {
	return append([]byte(fmt.Sprintf(header, s.Config.URL)), list.Bytes()...)
}
