package syncer

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/crypto/ssh"

	"github.com/myhro/ssh-keys/internal/config"
	"github.com/myhro/ssh-keys/internal/fetch"
)

type setup struct {
	ETagFile string
	File     string
	Syncer   *Syncer
}

func publicKey(t *testing.T) string {
	t.Helper()

	pub, _, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generating key: %v", err)
	}
	key, err := ssh.NewPublicKey(pub)
	if err != nil {
		t.Fatalf("converting key: %v", err)
	}

	return strings.TrimSpace(string(ssh.MarshalAuthorizedKey(key)))
}

func newSetup(t *testing.T, handler http.HandlerFunc) *setup {
	t.Helper()

	server := httptest.NewServer(handler)
	t.Cleanup(server.Close)

	dir := t.TempDir()
	cfg := &config.Config{
		ETagFile: filepath.Join(dir, "authorized_keys.etag"),
		File:     filepath.Join(dir, "authorized_keys"),
		URL:      server.URL,
	}

	return &setup{
		ETagFile: cfg.ETagFile,
		File:     cfg.File,
		Syncer: &Syncer{
			Client: fetch.New(),
			Config: cfg,
		},
	}
}

func read(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}

	return string(data)
}

func write(t *testing.T, path string, data string) {
	t.Helper()

	err := os.WriteFile(path, []byte(data), 0o600)
	if err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}

func TestRun(t *testing.T) {
	key := publicKey(t)
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("ETag", `"abc123"`)
		w.Write([]byte(key))
	})

	err := s.Syncer.Run(context.Background())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := read(t, s.File)
	if !strings.HasPrefix(content, "# Auto-generated by ssh-keys from ") {
		t.Fatalf("expected a generated header, got %q", content)
	}
	if !strings.HasSuffix(content, key+"\n") {
		t.Fatalf("expected the file to end with the key, got %q", content)
	}
	etag := read(t, s.ETagFile)
	if etag != `"abc123"`+"\n" {
		t.Fatalf(`expected "abc123", got %q`, etag)
	}
}

func TestRunNotModified(t *testing.T) {
	sent := ""
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		sent = r.Header.Get("If-None-Match")
		w.WriteHeader(http.StatusNotModified)
	})
	write(t, s.File, "current keys\n")
	write(t, s.ETagFile, `"abc123"`+"\n")

	err := s.Syncer.Run(context.Background())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if sent != `"abc123"` {
		t.Fatalf(`expected the cached etag to be sent, got %q`, sent)
	}
	content := read(t, s.File)
	if content != "current keys\n" {
		t.Fatalf("expected the file to be untouched, got %q", content)
	}
}

func TestRunMissingTargetIgnoresETag(t *testing.T) {
	key := publicKey(t)
	sent := "unset"
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		sent = r.Header.Get("If-None-Match")
		w.Write([]byte(key + "\n"))
	})
	write(t, s.ETagFile, `"abc123"`+"\n")

	err := s.Syncer.Run(context.Background())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if sent != "" {
		t.Fatalf("expected no etag to be sent, got %q", sent)
	}
	content := read(t, s.File)
	if !strings.HasSuffix(content, key+"\n") {
		t.Fatalf("expected the key to be written, got %q", content)
	}
}

func TestRunKeepsCurrentKeysOnFailure(t *testing.T) {
	tests := []struct {
		name   string
		status int
		body   string
	}{
		{
			name:   "invalid key",
			status: http.StatusOK,
			body:   "ssh-ed25519 not-a-real-key\n",
		},
		{
			name:   "empty body",
			status: http.StatusOK,
		},
		{
			name:   "not found",
			status: http.StatusNotFound,
			body:   "404 page not found\n",
		},
		{
			name:   "server error",
			status: http.StatusInternalServerError,
			body:   "boom\n",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("ETag", `"new"`)
				w.WriteHeader(tc.status)
				w.Write([]byte(tc.body))
			})
			write(t, s.File, "current keys\n")
			write(t, s.ETagFile, `"abc123"`+"\n")

			err := s.Syncer.Run(context.Background())
			if err == nil {
				t.Fatal("expected an error, got nil")
			}

			content := read(t, s.File)
			if content != "current keys\n" {
				t.Fatalf("expected the file to be untouched, got %q", content)
			}

			etag := read(t, s.ETagFile)
			if etag != `"abc123"`+"\n" {
				t.Fatalf("expected the etag to be untouched, got %q", etag)
			}
		})
	}
}

func TestRunWithoutETagHeader(t *testing.T) {
	key := publicKey(t)
	s := newSetup(t, func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(key + "\n"))
	})

	err := s.Syncer.Run(context.Background())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	_, err = os.Stat(s.ETagFile)
	if !os.IsNotExist(err) {
		t.Fatal("expected no etag file to be written")
	}
}
